package com.aucean.vmtest.mvvm.bindingmodel

import android.text.Html
import com.aucean.vmtest.mvvm.dataprovider.ArticleDetailRawDataModel

/**
 * Generated by MVVMActivityTemplate
 */
class ArticleDetailBindingModel{
    var imgUrl: String = ""
    var title: String = ""
    var summary: String = ""
    var content: String = ""
}