package com.aucean.vmtest.mvvm.bindingmodel

/**
 * Generated by DataProviderTemplate
 */
typealias VmTemplateExampleBindingModel = List<VmTemplateExampleBindingModelItem>
class VmTemplateExampleBindingModelItem(
        var imgUrl: String,
        var title: String,
        var summary: String,
        var postId: Int
)