package com.aucean.vmtest.activity

import com.aucean.vmtest.mvvm.viewmodel.ArticleDetailViewModel
import android.databinding.DataBindingUtil
import android.arch.lifecycle.ViewModelProviders
import android.net.Uri
import com.aucean.vmtest.databinding.ActivityArticleDetailBinding
import android.os.Bundle
import com.aucean.vmtest.R
import android.support.v7.app.AppCompatActivity
import com.squareup.picasso.Picasso

/**
 * Generated by MVVMActivityTemplate
 */

/**
 * 所有与UI没关的代码都不应该写在这里，而是在ViewModel，或者抽象到一个Helper里边实现
 */
class ArticleDetailActivity : AppCompatActivity() {
    companion object {
        const val POST_ID = "postId"
        const val IMAGE_URL = "image_url"
    }
    internal lateinit var mBinding: ActivityArticleDetailBinding


    override fun onCreate(savedInstanceState: Bundle?) {
        super.onCreate(savedInstanceState)
        mBinding = DataBindingUtil.setContentView<ActivityArticleDetailBinding>(this, R.layout.activity_article_detail)


        val viewModel: ArticleDetailViewModel  = ViewModelProviders.of(this).get(ArticleDetailViewModel::class.java)

        mBinding.setLifecycleOwner(this)
        mBinding.bindingModel = viewModel.bindingModel

        // 获取数据
        // e.g.
        //   mViewModel.getData())
        val postId = intent.getIntExtra(POST_ID, 0)
        viewModel.getData(postId)

         val imgUrl = intent.getStringExtra(IMAGE_URL)
        Picasso.get().load(imgUrl).into(mBinding.picture)
    }

    override fun onBackPressed() {
        finishAfterTransition()
    }
}