package ${packageName}.activity

import ${packageName}.mvvm.viewmodel.${className}ViewModel
import android.databinding.DataBindingUtil
import android.arch.lifecycle.ViewModelProviders
import ${packageName}.databinding.Activity${className}Binding
import android.os.Bundle
import ${packageName}.R
import android.support.v7.app.AppCompatActivity

/**
 * Generated by MVVMActivityTemplate
 */

/**
 * 所有与UI没关的代码都不应该写在这里，而是在ViewModel，或者抽象到一个Helper里边实现
 */
class ${className}Activity : AppCompatActivity() {

    internal lateinit var mBinding: Activity${className}Binding


    override fun onCreate(savedInstanceState: Bundle?) {
        super.onCreate(savedInstanceState)
        mBinding = DataBindingUtil.setContentView<Activity${className}Binding>(this, R.layout.${activityLayoutName})
        

        val mViewModel: ${className}ViewModel = ViewModelProviders.of(this).get(${className}ViewModel::class.java)

        mBinding.setLifecycleOwner(this)
        mBinding.bindingModel = viewModel.bindingModel

       // 获取数据
       // e.g.
       //   viewModel.getData())
    }
}