package com.aucean.vmtest.mvvm.viewmodel

import android.text.Html
import com.aucean.vmtest.mvvm.BaseViewModel
import com.aucean.vmtest.mvvm.GlhLiveData
import com.aucean.vmtest.mvvm.dataprovider.ArticleDetailDataProvider
import com.aucean.vmtest.mvvm.dataprovider.ArticleDetailApiParams
import com.aucean.vmtest.mvvm.dataprovider.ArticleDetailRawDataModel
import com.aucean.vmtest.mvvm.bindingmodel.ArticleDetailBindingModel

/**
 * Generated by MVVMActivityTemplate
 */
class ArticleDetailViewModel
    : BaseViewModel() {
    private val currentDataProvider = ArticleDetailDataProvider()

    val bindingModel = object : GlhLiveData<ArticleDetailBindingModel, ArticleDetailRawDataModel>() {
        override fun converter(data: ArticleDetailRawDataModel): ArticleDetailBindingModel? {
            return ArticleDetailBindingModel().apply {
                imgUrl = data.coverImageUrl
                title = data.title
                /**
                 * 模拟根据业务需求对网络返回数据进行处理
                 */
                summary = Html.fromHtml(data.summary).toString()
                content = Html.fromHtml(data.content).toString()
            }
        }
    }

    fun getData(poatId: Int) {
        currentDataProvider.getData(ArticleDetailApiParams(poatId), bindingModel, {})
    }

}