package com.aucean.vmtest.mvvm.dataprovider

import android.arch.persistence.room.Entity
import android.arch.persistence.room.PrimaryKey
import android.util.Log
import com.aucean.vmtest.database.AppDatabase
import com.aucean.vmtest.mvvm.*
import io.reactivex.Observable
import io.reactivex.schedulers.Schedulers

/**
 * Generated by MVVMActivityTemplate
 */
class ArticleDetailDataProvider
    : BaseDataProviderWithCache<ArticleDetailApiParams, ArticleDetailRawDataModel>(ArticleDetailNetWorkDataProvider()) {

    companion object {
        private const val LOG_TAG = "ArticleDataProvider"
    }

    protected class ArticleDetailNetWorkDataProvider : BaseNetworkProvider<ArticleDetailApiParams, ArticleDetailRawDataModel>() {
        override fun getDataFromNetwork(params: ArticleDetailApiParams): Observable<ResponseModel<ArticleDetailRawDataModel>> {
            /* e.g.
             *      return HttpHelper.getServer().getExampleData(params.stockType, params.stockCode)
            */
            return HttpHelper.getServer().getArticleDetail(params.postId)
        }
    }

    override fun getCacheData(param: ArticleDetailApiParams): Optional<ArticleDetailRawDataModel> {
        val cache = AppDatabase.db.articleDao().loadArticle(param.postId)
        if (cache != null && !cache.isEmpty()) {
            Log.i(LOG_TAG, "return cached article[postId = ${param.postId}]: ${cache[0]}" )
            return OptionalImpl(cache[0])
        } else {
            return OptionalImpl()
        }
    }

    override fun saveData(param: ArticleDetailApiParams, data: ArticleDetailRawDataModel) {
        Log.i(LOG_TAG, "store article for ${data.postId}")
        AppDatabase.db.articleDao().insertArticle(data)
    }
}

class ArticleDetailApiParams(var postId: Int)
/**
 * Api 返回数据Bean对象(网络层数据Bean)
 */
@Entity(tableName = "articles")
class ArticleDetailRawDataModel(@PrimaryKey val postId: Int,
    val type: Int,
    val title: String,
    val content: String,
    val createDate: Int,
    val userId: Int,
    val nickname: String,
    val avatar: String,
    val summary: String,
    val coverImageUrl: String
)