package com.aucean.vmtest.mvvm.dataprovider

import io.reactivex.Observable
import com.aucean.vmtest.mvvm.ResponseModel
import com.aucean.vmtest.mvvm.BaseDataProvider
import com.aucean.vmtest.mvvm.BaseNetworkProvider
import com.aucean.vmtest.mvvm.HttpHelper

/**
 * Generated by MVVMActivityTemplate
 */
class ArticleDetailDataProvider
    : BaseDataProvider<ArticleDetailApiParams, ArticleDetailRawDataModel>(ArticleDetailNetWorkDataProvider()) {

    protected class ArticleDetailNetWorkDataProvider : BaseNetworkProvider<ArticleDetailApiParams, ArticleDetailRawDataModel>() {
        override fun getDataFromNetwork(params: ArticleDetailApiParams): Observable<ResponseModel<ArticleDetailRawDataModel>> {
            /* e.g.
             *      return HttpHelper.getServer().getExampleData(params.stockType, params.stockCode)
            */
            return HttpHelper.getServer().getArticleDetail(params.postId)
        }
    }
}

class ArticleDetailApiParams(var postId: Int)
/**
 * Api 返回数据Bean对象(网络层数据Bean)
 */
class ArticleDetailRawDataModel(
    val postId: Int,
    val type: Int,
    val title: String,
    val content: String,
    val createDate: Int,
    val userId: Int,
    val nickname: String,
    val avatar: String,
    val summary: String,
    val coverImageUrl: String
)